sudo: false

matrix:
    include:
      - language: node_js
        node_js:
            - node
        install:
            - cd src/client
            - npm i
        script:
            - npm run lint
            - npm test

notifications:
    email: false